### ISSUE TITLE
JOSS Review: Tests

### ISSUE THREAD

**Issue by rreinecke** [keurfonluu/toughio#52]
* How can a potential user run the tests? Is that described somewhere?
* Do you supply example files? (I don't use Though so I don't have anything to test your software package properly, this might happen to a potential user as well). If so, where do I find a description on how to use them with your tool.

**Comment by rreinecke** [comment]
#openjournals/joss-reviews/issues/2412

**Comment by rreinecke** [comment]
The first question has been addressed by #53 
Second would be important though for me to able to verify if your tool does what it is suppose to do

**Comment by keurfonluu** [comment]
Hi,

I've added a complete example problem (from pre- to post-processing) in the documentation:
https://keurfonluu.github.io/toughio//examples/co2_leakage_along_a_fault/index.html

This gallery is automatically generated from [`./examples`](https://github.com/keurfonluu/toughio/tree/master/examples). Input and output files are included so all scripts should run (even without Gmsh and TOUGH).

Note that the documentation has been moved from ReadtheDocs to GitHub-Pages since RTD is too limited in terms of functionalities (no support for git-lfs and headless display in my case).

Otherwise, other minor features can be automatically tested running `pytest` (91% coverage right now, the remaining 9% mostly corresponding to input argument checking).

For both doc and test, some files are stored as LFS, please run `git lfs pull` before running the example scripts and automated tests.

**Comment by rreinecke** [comment]
Great @keurfonluu ! Could you please add these important hints also to the README. This will help potential users to easily explore everything your project has to offer.

**Comment by rreinecke** [comment]
Downloading examples/co2_leakage_along_a_fault/CO2TAB (624 KB)
Error downloading object: examples/co2_leakage_along_a_fault/CO2TAB (d5376c1): Smudge error: Error downloading examples/co2_leakage_along_a_fault/CO2TAB (d5376c1145adba382418b4fa604074a10aaa99162e49602e789a92b75138da14): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /tmp/toughio/.git/lfs/logs/20200708T071124.214786408.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: examples/co2_leakage_along_a_fault/CO2TAB: smudge filter lfs failed

**Comment by keurfonluu** [comment]
Yeah, it seems that Travis CI has consumed my monthly LFS bandwidth quota in a matter of hours (which seems to be a common [issue](https://github.com/travis-ci/travis-ci/issues/8787). I'll investigate and then restore access to LFS. Otherwise, I'll have to give up on LFS.

**Comment by keurfonluu** [comment]
I found a workaround and reenabled access to LFS by purchasing a data pack. You should be good to go.

> Great @keurfonluu ! Could you please add these important hints also to the README. This will help potential users to easily explore everything your project has to offer.

Done ! Thanks !

**Comment by rreinecke** [comment]
> Otherwise, other minor features can be automatically tested running `pytest` (91% coverage right now, the remaining 9% mostly corresponding to input argument checking).

pytest only works if the module is already installed. With a clean clone python is not able to find the module.

**Comment by keurfonluu** [comment]
> pytest only works if the module is already installed. With a clean clone python is not able to find the module.

You are right, it should be clearer in the README now.

**Comment by rreinecke** [comment]
> > pytest only works if the module is already installed. With a clean clone python is not able to find the module.
> 
> You are right, it should be clearer in the README now.

It should be possible to also load the local modules with pytest without having to install everything first. But thats also a solution that works for me
